baseurl: https://rweldzius.github.io/psc4175/
defaultContentLanguage: en
title: "Introduction to Data Science"
theme: hugo-academic
instructor: "Ryan Weldzius"

# ------------------
# Building options
# ------------------
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: True

# No taxonomy
disableKinds:
  - taxonomy
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: false
  tableOfContents:
    startLevel: 2
    endLevel: 4
imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart

copyright: ""
enableGitInfo: true
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true
pagination:
  pagerSize: 10
enableEmoji: true
footnotereturnlinkcontents: <sup>^</sup>

# ----------------
# Output options
# ----------------
outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - SearchIndex
  section:
    - HTML
    - RSS

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "search"
    isPlainText: true
    notAlternative: true
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest
mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - "\\.knit\\.md$"
  - "\\.utf8\\.md$"
