---
title: "Syllabus for PSC 4175: Introduction to Data Science"
slug: syllabus
summary: "Information about the content and policies for PSC 4175"
citeproc: true
layout: assignments/single
output:
  blogdown::html_page:
      toc: TRUE
---


## Head Instructor

Prof. Ryan Weldzius  
Email: [ryan.weldzius@villanova.edu](mailto:ryan.weldzius@villanova.edu)
Web: [ryanweldzius.com](http://ryanweldzius.com)  

### Office Hours

  * Tuesdays, 2:30pm-4:30pm Villanova time
  * You must make an appointment for office hours here: https://calendly.com/weldzius/officehours
  * If you cannot make my office hours, please email me your availability at least 24-hours in advance and we can try to find a time that works.

## Course Description

The use of large, quantitative data sets is increasingly central in social science.  Whether one seeks to understand political behavior, economic outcomes, or violent conflict, the availability of large quantities of data has changed the study of social phenomena. In this course, students will learn about data acquisition, management, and visualization — what we call data science — to answer exciting questions in the social sciences. Whereas most data-related courses focus exclusively on probability theory, matrix algebra, and/or statistical estimation, our main focus will be on the computational tools of data science. Students will leave the course with the ability to acquire, clean, visualize, and analyze various types of political data using the statistical programming language R, which will set them up for success in future statistical courses (as well as the post-graduation job market). No prior background in statistics is required, but students should be familiar with how to use a computer and have a willingness to learn a variety of data science tools. 

The contents of this repository represent a work-in-progress and revisions and edits are likely frequent.

The main text for the course is "R For Data Science" which can be assessed free online [here](https://r4ds.hadley.nz). Note that there are no assigned readings from this book; the material is synthesized in the daily homework assignments. However, should you need another source with more detail, you'll find most of the topics we cover in this course in this book.

Villanova has an enterprise site license for Microsoft’s Copilot chat application, which is built off of Open A.I.  Copilot is available to all faculty, staff, and students [here](https://copilot.microsoft.com).

**Class time and location**: Asynchronous (online) Tuesdays; Synchronous (online) Thursdays 2:30-3:45pm.

## Required Applications

### Blackboard

This is the course management software used at Villanova University to support course learning. It is clunky, not user-friendly, and is thankfully on its way out soon. For these reasons, I will only utilize Blackboard to post course materials (e.g., additional readings), for you to submit your assignments, and to see your grades.

### Campuswire

I have set up a Campuswire workspace for our use this semester to help us better communicate with each other. You will need to create an account and join our workspace by following [this link](https://campuswire.com/p/G9062A201). The Code/PIN can be found on the first email I sent to the class. You are encouraged to adopt these [Slack etiquette tips](https://slack.com/blog/collaboration/etiquette-tips-in-slack). Most likely, you will utilize a similar communication system at a future job, so use this time wisely as you adopt best practices. 

Here is the list of channels you should see upon joining the Campuswire workspace:

  * Class feed: A space to post questions and respond to other posts.

  * #announcements: A space for all course announcements.

  * #general: A space for you to share and discuss stories you've seen in the news or on social media that are relevant to our class.

  * Calendar: Not used. See [Schedule](/schedule). 

  * Files: Not used. See [Resources](/resources). 

  * Grades: Not used. See Blackboard. 

<!-- ### GitHub -->

<!-- I have created a [GitHub](https://github.com/rweldzius/PSC4175_SUM2025/tree/main) repository to prepare and share all course-related content. This very syllabus is available as the repository's README and all links below are connected to the appropriate folders, sub-folders, and files in this repository. -->

<!-- You are expected to adopt the following workflow for this class: -->

<!--   1. Prior to viewing each lecture, download the appropriate homework `.Rmd` file, open it in `RStudio`, and read through it. This is your primary homework assignment. As you work through it, try to tweak some of the code and answer the toy examples where provided. Each time you make a change, click the knit button in `RStudio` to see if everything still loads. You may find it useful to read through the homework first, then watch the lecture, then go back to the homework and complete the examples. These knitted files should be uploaded to Blackboard by midnight on the day the lecture is assigned; see schedule below. -->

<!--   2. During each lecture, create a new `.Rmd` file to take notes in. As with the homework, you should be tweaking and adjusting things on your own, extending your learning beyond what is covered in lecture. -->

<!--   3. After each lecture, tweak the notes `.Rmd` file further to test out new ideas that you come up with which were not covered in the lecture. Each lecture's slides will be made available as `PDF` for you use to help you review.  -->


## Evaluation & Responsibilities  

As with learning any new topic or language, the best strategy is to put in a little effort every day. To this end, you will be assigned homework assignments for each class. These are your primary readings, so take your time working through them. You must submit each homework to Blackboard by Tuesday at 10:00pm on the date they are assigned. 

You will be assigned bi-weekly problem sets that will test your ability to apply what you've learned in the lectures. These problem sets are assigned on the Monday of each week and are due by **11:59PM Villanova time the following Friday**. You are welcome to collaborate on these problem sets, and are encouraged to ask questions on the Class feed on Campuswire.

The final grade is calculated as a weighted average of these components with the following weights:

  * **Homeworks** (35 points): There are 14 homeworks over the semester. Each will be worth between 1 and 3 points depending on their length/difficulty (total 35 points). Due on Tuesdays by 10:00pm. 

  * **Problem sets** (35 points): 6 in total worth 7 points each, but only 5 will be graded (one freebie!). There will be one extra credit point available in each of the problem sets. 5 problem sets: 35 total points (35% of your final grade), plus 5 extra credit points available (+5 points) and I will still count the ungraded problem set as extra credit (+8 points). 

  * **Final Project**: Worth 20 points (write-up 15 points, presentation and comments 5 points). The final project for the course will be a data analysis project where students will find a dataset of interest, state an interesting research question about that data, and answer this question using that data. Students may work individually, or can work in groups of up to 3 students. Your proposal is due by Week 7 (a short description of your research question, argument, and potential data sources). In the final week of classes, you will present your work to the class in a short 5 minute presentation (recorded). Each student will watch your video and provide one positive comment, one looming question, and one helpful tip to improve the project. Final papers due by **Tuesday, December 16 at 5:00pm.**

  * **Attendance & Participation**: Worth 10 points. You are required to show up to our Thursday classes and participate. 

See the table below for a breakdown of the percentages, points, and extra credit.

| Item | Percent | Points | EC | Max |
|:-----|:-----:|:-----:|:-----:|:-----:|
| pset0 | 0% | 0 | 0 | 0 |
| pset1 | 7% | 7 | 1 | 8 |
| pset2 | 7% | 7 | 1 | 8 |
| pset3 | 7% | 7 | 1 | 8 |
| pset4 | 7% | 7 | 1 | 8 |
| pset5 | 7% | 7 | 1 | 8 |
| pset6 | 0% | 0 | 8 | 8 |
| Homeworks | 35% | 35 | 0 | 35 |
| Final Project | 20% | 20 | 0 | 20 |
| Attendance/Participation | 10% | 10 | 0 | 10 |
| **Totals** | **100%** | **100** | **13** | **113** |

Letter grades are determined as per the standard Villanova grading system:

  | Letter Grade | Score Range |
|--------------|-------------|
| A            | 94+         |
| A−           | 90–93       |
| B+           | 87–89       |
| B            | 84–86       |
| B−           | 80–83       |
| C+           | 77–79       |
| C            | 74–76       |
| C−           | 70–73       |
| D+           | 67–69       |
| D            | 64–66       |
| D−           | 60–63       |
| F            | <60         |

## Course Policies

### Attendance

This course is a mix of asynchronous (Tuesdays) and synchronous (Thursdays, 2:30-3:45pm). You are required to attend all synchronous sessions and participate in the discussion. 

### Late Assignments

Late homeworks will not be accepted. Every problem set is assigned on a Monday and due on Blackboard by **11:59PM Villanova time on the following Friday**. Problem sets should be submitted via Blackboard. The problem sets are designed to require no more than a few hours to complete. Late submissions will be **penalized 1 point off for each day late**. After three days, problem sets will no longer be accepted and will be scored 0. 

### Academic Honor Code

All students are expected to uphold Villanova’s Academic Integrity Policy and Code. Any incident of academic dishonesty will be reported to the Dean of the College of Liberal Arts and Sciences for disciplinary action. You may view the [University’s Academic Integrity Policy and Code](https://www1.villanova.edu/villanova/provost/resources/student/policies/integrity/code.html) for a detailed description.

If a student is found responsible for an academic integrity violation, which results in a grade penalty, they may not WX the course unless they are approved to WX for significant medical reasons. Students applying for a WX based on significant medical reasons, must submit documentation and their request for an exception will be considered.

Collaboration is the heart of data science, but your work on your assignments should be your own. Please be careful not to plagiarize. The above link is a very helpful guide to understanding plagiarism. In particular, while students are invited to work on problem sets together, collaboration is prohibited on the midterm and final exams.

Copilot and related Large Language Models (LLMs) are essential tools in the data scientist's toolkit, and acceptable resources for completing the assignments and learning concepts at a deeper level. However, graded assignments cannot be generated purely by these tools. All assignments must include a log of the Copilot (or other AI programs) prompts and resulting output used to complete the assignment. **If you are found to have used AI to complete an assignment with no citation and printed output, you will receive a zero for that assignment. A second infraction will lead to a failure of the class.**

### Office for Access & Disability Services (ADS) and Learning Support Services (LSS)

It is the policy of Villanova to make reasonable academic accommodations for qualified individuals with disabilities. All students who need accommodations should go to Clockwork for Students via myNOVA to complete the Online Intake or to send accommodation letters to professors. Go to the LSS website http://learningsupportservices.villanova.edu or the ADS website https://www1.villanova.edu/university/student-life/ods.html for registration guidelines and instructions. If you have any questions please contact LSS at 610-519-5176 or [learning.support.services@villanova.edu](mailto:learning.support.services@villanova.edu), or ADS at 610-519-3209 or [ods@villanova.edu](mailto:ods@villanova.edu).

### Absences for Religious Holidays

Villanova University makes every reasonable effort to allow members of the community to observe their religious holidays, consistent with the University’s obligations, responsibilities, and policies. Students who expect to miss a class or assignment due to the observance of a religious holiday should discuss the matter with their professors as soon as possible, normally at least two weeks in advance. Absence from classes or examinations for religious reasons does not relieve students from responsibility for any part of the course work required during the absence. [https://www1.villanova.edu/villanova/provost/resources/student/policies/religiousholidays.html]().

## Helpful Resources

See [Resources](/resources/)


## Acknowledgements

The contents of this course are influenced by Prof. James H. Bisbee who teaches a similar course at Vanderbilt University. I am indebted to him for making his course materials available. The design of the webpage is inspired by Matthew Blackwell. 
