# GitHub Actions workflow for Hugo Blogdown (R) deployment
# This workflow builds and deploys a Hugo Blogdown site to GitHub Pages

name: Build and Deploy Blogdown Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.125.7"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Set up Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/project_packages.R') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R package dependencies from DESCRIPTION
        run: |
          Rscript -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
          Rscript -e 'if (!tinytex::is_tinytex()) tinytex::install_tinytex()'

      - name: Build site via blogdown
        run: |
          Rscript -e 'blogdown::install_hugo(version = Sys.getenv("HUGO_VERSION"), force = TRUE)'
          Rscript -e 'blogdown::build_site()'

      - name: Disable Jekyll
        run: touch public/.nojekyll    

      - name: Upload public dir as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
